server:
  port: 8080
  servlet:
    context-path: /random

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.43.242:3306/random_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&nullCatalogMeansCurrent=true
#    url: jdbc:mysql://47.93.43.242:3306/random_test&useSSL=true&requireSSL=true&serverTimezone=UTC&verifyServerCertificate=true&trustCertificateKeyStoreUrl=file:path/to/ca.pem&trustCertificateKeyStorePassword=password
    username: root
    password: 200087
  mvc:
    pathmatch:
      #解决spring boot和swagger版本不兼容问题
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath*:mapper/*.xml

#sql执行日志级别，显示sql语句
logging:
  level:
    com:
      example:
        business:
          mapper: debug